# Generated by Django 2.2 on 2020-02-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20200217_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcontrolindicators',
            name='cost_per_wan',
        ),
        migrations.RemoveField(
            model_name='internalcontrolindicators',
            name='field_management_compliance',
        ),
        migrations.RemoveField(
            model_name='internalcontrolindicators',
            name='month_medical_expenses',
        ),
        migrations.RemoveField(
            model_name='monthlyperformance',
            name='field_management',
        ),
        migrations.RemoveField(
            model_name='monthlyperformance',
            name='overall_cost',
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='actual_cost',
            field=models.IntegerField(default=0, verbose_name='实际成本'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='actual_management_compliance',
            field=models.IntegerField(default=0, verbose_name='实际管理符合数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='actual_medical_expenses',
            field=models.IntegerField(default=0, verbose_name='实际医药费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='order_money',
            field=models.IntegerField(default=0, verbose_name='订单额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='target_comprehensive_cost',
            field=models.FloatField(default=0, verbose_name='目标综合成本'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='target_management_compliance',
            field=models.IntegerField(default=0, verbose_name='目标管理符合数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='target_medical_expenses',
            field=models.FloatField(default=0, verbose_name='目标医药费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='field_management_well_rate',
            field=models.FloatField(default=0, verbose_name='现场管理符合率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyperformance',
            name='month_dig_cost',
            field=models.FloatField(default=0, verbose_name='当月挖掘成本'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='date',
            field=models.DateTimeField(verbose_name='订单时间'),
        ),
    ]
