# Generated by Django 2.2 on 2020-02-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20200219_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_cost',
            field=models.IntegerField(blank=True, verbose_name='实际成本'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_delivery',
            field=models.DateTimeField(blank=True, verbose_name='实际交期'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_management_compliance',
            field=models.IntegerField(blank=True, verbose_name='实际管理符合数'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_medical_expenses',
            field=models.IntegerField(blank=True, verbose_name='实际医药费'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_well_done_rate',
            field=models.FloatField(blank=True, verbose_name='实际成品率'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='finished_number',
            field=models.IntegerField(blank=True, verbose_name='完成数'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='unfinished_number',
            field=models.IntegerField(blank=True, verbose_name='未完成数'),
        ),
    ]
