# Generated by Django 2.2 on 2020-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20200219_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constantdata',
            name='annual_target_award',
        ),
        migrations.RemoveField(
            model_name='constantdata',
            name='annual_target_turnover',
        ),
        migrations.RemoveField(
            model_name='constantdata',
            name='field_management_compliance_target_number',
        ),
        migrations.RemoveField(
            model_name='constantdata',
            name='month_plan_order_number',
        ),
        migrations.RemoveField(
            model_name='constantdata',
            name='target_cost',
        ),
        migrations.AddField(
            model_name='constantdata',
            name='target_comprehensive_cost_rate',
            field=models.FloatField(default=1, verbose_name='目标综合成本百分比'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constantdata',
            name='target_management_compliance_value',
            field=models.IntegerField(default=1, verbose_name='目标管理符合数值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constantdata',
            name='target_medical_expenses_rate',
            field=models.FloatField(default=1, verbose_name='目标医药费百分比'),
            preserve_default=False,
        ),
    ]
