# Generated by Django 2.2 on 2020-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20200220_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_delivery',
            field=models.DateField(null=True, verbose_name='实际交期'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='date',
            field=models.DateField(verbose_name='订单时间'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='scheduled_delivery',
            field=models.DateField(verbose_name='计划交期'),
        ),
    ]
