# Generated by Django 2.2 on 2020-02-20 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20200220_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcontrolindicators',
            name='date',
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='订单时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_delivery',
            field=models.DateTimeField(null=True, verbose_name='实际交期'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='scheduled_delivery',
            field=models.DateTimeField(verbose_name='计划交期'),
        ),
    ]
