# Generated by Django 2.2 on 2020-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20200220_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantdata',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
