# Generated by Django 2.2 on 2020-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_auto_20200222_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_cost',
            field=models.FloatField(null=True, verbose_name='实际成本'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_medical_expenses',
            field=models.FloatField(null=True, verbose_name='实际医药费'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='order_money',
            field=models.FloatField(verbose_name='订单额'),
        ),
        migrations.AlterField(
            model_name='monthlysalesdata',
            name='inventory',
            field=models.IntegerField(verbose_name='库存量'),
        ),
        migrations.AlterField(
            model_name='quarterlysalesdata',
            name='inventory',
            field=models.IntegerField(verbose_name='库存量'),
        ),
    ]
