# Generated by Django 2.2 on 2020-03-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_auto_20200222_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='日志时间')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('job_number', models.CharField(max_length=100, verbose_name='工号')),
                ('action', models.CharField(max_length=254, verbose_name='动作描述')),
                ('result', models.CharField(max_length=20, verbose_name='操作结果')),
            ],
            options={
                'verbose_name': '日志表',
                'verbose_name_plural': '日志表',
            },
        ),
    ]
