# Generated by Django 2.2 on 2020-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0013_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantdata',
            name='annual_target_award',
            field=models.FloatField(default=1, verbose_name='年度目标奖金额'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constantdata',
            name='annual_target_turnover',
            field=models.FloatField(default=1, verbose_name='年度目标营业额'),
            preserve_default=False,
        ),
    ]
