# Generated by Django 2.2 on 2020-03-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0014_auto_20200301_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('quarter', models.IntegerField(verbose_name='季度')),
                ('turnover_award', models.FloatField(verbose_name='营业额所得奖金额')),
                ('operating_rate_award', models.FloatField(verbose_name='营业费率所得奖金额')),
                ('repaid_rate_award', models.FloatField(verbose_name='回款率所得奖金额')),
                ('inventory_rate_award', models.FloatField(verbose_name='库存率所得奖金额')),
                ('profit_rate_award', models.FloatField(verbose_name='利润率所得奖金额')),
                ('total', models.FloatField(verbose_name='合计')),
            ],
            options={
                'verbose_name': '季度绩效奖金额',
                'verbose_name_plural': '季度绩效奖金额',
            },
        ),
    ]
