# Generated by Django 2.2 on 2020-03-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0016_quarterlyawardformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('who', models.CharField(max_length=100, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '公告表',
                'verbose_name_plural': '公告表',
            },
        ),
    ]
