# Generated by Django 2.2 on 2020-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0017_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ways', models.CharField(max_length=200, verbose_name='系统登录方式')),
            ],
            options={
                'verbose_name': '系统配置表',
                'verbose_name_plural': '系统配置表',
            },
        ),
    ]
