# Generated by Django 2.2 on 2020-03-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0018_systemconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('view_monthly_sales_data', '查看月度营业数据'), ('manage_monthly_sales_data', '管理月度营业数据'), ('view_quarterly_sales_data', '查看季度营业数据'), ('view_internal_control_indicators', '查看内控指标汇总'), ('manage_internal_control_indicators', '管理内控指标汇总'), ('view_monthly_performance', '查看月度绩效考核结果'), ('view_quarterly_performance', '查看季度绩效考核结果'), ('manage_constant_data', '管理常量数据'), ('manage_formula', '管理报表公式'), ('manage_user', '管理用户'), ('manage_permission', '管理授权'), ('user_logs', '查看用户操作日志'), ('manage_backups', '管理系统数据库备份'))},
        ),
    ]
