# Generated by Django 2.2 on 2020-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0020_auto_20200305_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_A',
            field=models.CharField(default='当月订单按时完成数', max_length=200, verbose_name='当月订单按时完成数'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_B',
            field=models.CharField(default='当月订单计划完成数', max_length=200, verbose_name='当月订单计划完成数'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_C',
            field=models.CharField(default='当月实际产品率累加', max_length=200, verbose_name='当月实际产品率累加'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_D',
            field=models.CharField(default='当月目标医药费累加', max_length=200, verbose_name='当月目标医药费累加'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_E',
            field=models.CharField(default='当月实际医药费累加', max_length=200, verbose_name='当月实际医药费累加'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_F',
            field=models.CharField(default='当月目标成本累加', max_length=200, verbose_name='当月目标成本累加'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_G',
            field=models.CharField(default='当月实际成本累加', max_length=200, verbose_name='当月实际成本累加'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_H',
            field=models.CharField(default='当月实际符合符合数', max_length=200, verbose_name='当月实际符合符合数'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='month_result_item_I',
            field=models.CharField(default='当月目标管理符合数', max_length=200, verbose_name='当月目标管理符合数'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_A',
            field=models.CharField(default='年度目标营业额', max_length=200, verbose_name='年度目标营业额'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_B',
            field=models.CharField(default='季度目标奖金额', max_length=200, verbose_name='季度目标奖金额'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_C',
            field=models.CharField(default='季度实际营业额', max_length=200, verbose_name='季度实际营业额'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_D',
            field=models.CharField(default='季度实际营业费率', max_length=200, verbose_name='季度实际营业费率'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_E',
            field=models.CharField(default='前三年营业费率参考值', max_length=200, verbose_name='前三年营业费率参考值'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_F',
            field=models.CharField(default='季度实际回款率', max_length=200, verbose_name='季度实际回款率'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_G',
            field=models.CharField(default='季度实际库存率', max_length=200, verbose_name='季度实际库存率'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_H',
            field=models.CharField(default='前三年库存率率参考值', max_length=200, verbose_name='前三年库存率率参考值'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_I',
            field=models.CharField(default='季度实际利润率', max_length=200, verbose_name='季度实际利润率'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_award_item_K',
            field=models.CharField(default='前三年利润率参考值', max_length=200, verbose_name='前三年利润率参考值'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_result_item_A',
            field=models.CharField(default='季度营业额', max_length=200, verbose_name='季度营业额'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_result_item_B',
            field=models.CharField(default='季度营业费用', max_length=200, verbose_name='季度营业费用'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_result_item_C',
            field=models.CharField(default='季度回款额', max_length=200, verbose_name='季度回款额'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_result_item_D',
            field=models.CharField(default='季度库存量', max_length=200, verbose_name='季度库存量'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quarter_result_item_E',
            field=models.CharField(default='季度利润额', max_length=200, verbose_name='季度利润额'),
        ),
    ]
