# Generated by Django 2.2 on 2020-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0021_auto_20200309_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='backup_to_email',
            field=models.EmailField(default='lvpeng990324@qq.com', max_length=254, verbose_name='数据库备份文件目标邮箱'),
            preserve_default=False,
        ),
    ]
