# Generated by Django 2.2 on 2020-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0023_systemconfig_days_to_auto_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('password', models.CharField(max_length=200, verbose_name='接口密码')),
                ('introduction', models.CharField(max_length=200, verbose_name='接口简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_enabled', models.BooleanField(verbose_name='是否启用')),
                ('called_times', models.BooleanField(verbose_name='调用次数')),
            ],
            options={
                'verbose_name': '接口表',
                'verbose_name_plural': '接口表',
            },
        ),
    ]
