# Generated by Django 2.2 on 2020-03-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0024_openapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openapi',
            name='called_times',
            field=models.IntegerField(verbose_name='调用次数'),
        ),
    ]
