# Generated by Django 2.2 on 2020-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0025_auto_20200312_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='openapi',
            name='opened_data',
            field=models.TextField(default='', verbose_name='开放的数据项'),
            preserve_default=False,
        ),
    ]
