# Generated by Django 2.2 on 2020-03-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0026_openapi_opened_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openapi',
            name='called_times',
            field=models.IntegerField(default=0, verbose_name='调用次数'),
        ),
    ]
