# Generated by Django 2.2 on 2020-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0028_auto_20200313_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='openapi',
            name='request_method',
            field=models.CharField(default='GET POST', max_length=20, verbose_name='请求方式'),
            preserve_default=False,
        ),
    ]
