# Generated by Django 2.2 on 2020-03-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0029_openapi_request_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='unionID',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='微信Id'),
        ),
    ]
