# Generated by Django 2.2 on 2020-04-11 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0030_userextension_unionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='actual_give_money_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='实际回款时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='operating_expenses',
            field=models.FloatField(default=0, verbose_name='营业费用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalcontrolindicators',
            name='scheduled_give_money_day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='计划回款时间'),
            preserve_default=False,
        ),
    ]
