# Generated by Django 2.2 on 2020-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0031_auto_20200411_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='actual_give_money_day',
            field=models.DateField(null=True, verbose_name='实际回款时间'),
        ),
        migrations.AlterField(
            model_name='internalcontrolindicators',
            name='operating_expenses',
            field=models.FloatField(null=True, verbose_name='营业费用'),
        ),
    ]
